package:
    name:           hidev
    namespace:      hidev
    label:          HiDev
    title:          HiDev - integrate your development
    type:           project
    forum:          https://forum.hiqdev.com/hidev
    homepage:       https://hidev.me/
    keywords:       build tool, task runner, code generator, continuous integration
    description:    Mix all the tools to make your code shine
    year:           2014
    src:            src

aliases:
    g: asdfasfas
