build:
    dependencies:
        before:
            - composer global require "fxp/composer-asset-plugin:~1.1" "yiisoft/yii2-composer:~2.0"
            - wget https://getcomposer.org/download/1.0.0-alpha11/composer.phar
            - php composer.phar install --no-interaction

imports:
    - php

