language: php
php:
    - 5.5
    - 5.6
    - 7
    - hhvm
sudo: false
install:
    - 'hidev travis/install'
script:
    - 'hidev travis/script'
cache:
    directories:
        - $HOME/.composer/cache
