package:
    name:           hidev
    namespace:      hidev
    label:          HiDev
    headline:       HiDev - integrated development
    title:          Task runner, code generator and build tool for continuos integration
    type:           project
    forum:          https://forum.hiqdev.com/hidev
    homepage:       https://hidev.me/
    keywords:       build tool, task runner, code generator, continuous integration
    year:           2014
    description:    |
        Features:
        - package management: composer.json, Packagist
        - release automation: README, LICENSE, CHANGELOG
        - code generation with php and twig templates
        - VCS integration: .gitignore, commits history
        - code quality: php-cs-fixer, VersionEye
        - testing: codeception

        And more planned. See [ROADMAP](https://github.com/hiqdev/hidev/blob/master/ROADMAP.md).

require:
    hiqdev/hidev-config:        "*@dev"
    hiqdev/hidev-config-php:    "*@dev"
