parent:
    github:         hiqdev/hidev-config

package:
    name:           hidev
    namespace:      hidev
    label:          HiDev
    title:          HiDev - integrate your development
    type:           project
    forum:          https://forum.hiqdev.com/hidev
    homepage:       https://hidev.me/
    keywords:       build tool, task runner, code generator, continuous integration
    description:    Mix all the tools to make your code shine
    year:           2014

composer.json:
    require:
        yiisoft/yii2:               '~2.0'
        yiisoft/yii2-twig:          '~2.0'
        symfony/yaml:               '~2.7'
        hiqdev/yii2-collection:     '*@dev'
        hiqdev/yii2-pluginmanager:  '*@dev'
        codegyre/robo:              '*'
    bin: [hidev]

php-cs-fixer:
    deps: .php_cs

