package:
    type:           project
    name:           hidev
    title:          Task runner, code generator and build tool for easier continuos integration
    headline:       HiDev
    keywords:       build tool, task runner, code generator, continuous integration
    namespace:      hidev
    description:    |
        Features:

        - package management: [Composer](https://getcomposer.org/), [Packagist](https://packagist.org/)
        - release automation: README, LICENSE, CHANGELOG, version bump
        - CI services: [Travis](https://travis-ci.org/), [Scrutinizer](https://scrutinizer-ci.com/)
        - testing: [PHPUnit](https://phpunit.de/), [Codeception](http://codeception.com/)
        - code quality: [PHP-CS-Fixer](http://cs.sensiolabs.org/), [VersionEye](https://www.versioneye.com/)
        - version control: .gitignore, commits history
        - PHAR building with [Box](https://github.com/box-project/box2)
        - code generation with php and twig templates

        And more planned. See [ROADMAP](ROADMAP.md).

plugins:
    hiqdev/hidev-box:           "*@dev"
    hiqdev/hidev-php:           "*@dev"
    hiqdev/hidev-readme:        "*@dev"
    hiqdev/hidev-travis:        "*@dev"
    hiqdev/hidev-vendor:        "*@dev"
    hiqdev/hidev-license:       "*@dev"
    hiqdev/hidev-phpunit:       "*@dev"
    hiqdev/hidev-composer:      "*@dev"
    hiqdev/hidev-scrutinizer:   "*@dev"
    hiqdev/hidev-php-cs-fixer:  "*@dev"

default:
    before:
        - version

