package:
    type:           project
    name:           hidev
    namespace:      hidev
    headline:       HiDev
    title:          Task runner, code generator and build tool for easier continuos integration
    forum:          http://forum.hiqdev.com/hidev
    keywords:       build tool, task runner, code generator, continuous integration
    description:    |
        Features:
        - package management: Composer, Packagist
        - release automation: README, LICENSE, CHANGELOG
        - code generation with php and twig templates
        - version control: .gitignore, commits history
        - code quality: PHP-CS-Fixer, VersionEye
        - testing: PHPUnit, Codeception

        And more planned. See [ROADMAP](ROADMAP.md).

require:
    hiqdev/hidev-box:           "*@dev"
    hiqdev/hidev-php:           "*@dev"
    hiqdev/hidev-readme:        "*@dev"
    hiqdev/hidev-travis:        "*@dev"
    hiqdev/hidev-vendor:        "*@dev"
    hiqdev/hidev-license:       "*@dev"
    hiqdev/hidev-phpunit:       "*@dev"
    hiqdev/hidev-composer:      "*@dev"
    hiqdev/hidev-scrutinizer:   "*@dev"
    hiqdev/hidev-php-cs-fixer:  "*@dev"

default:
    before:
        - version

dir:
    class:  directory
    file:   here1
