package:
    name:           hidev
    namespace:      hidev
    headline:       HiDev
    title:          Task runner, code generator and build tool for easier continuos integration
    type:           project
    forum:          http://forum.hiqdev.com/hidev
    keywords:       build tool, task runner, code generator, continuous integration
    year:           2014
    description:    |
        Features:
        - package management: composer.json, Packagist
        - release automation: README, LICENSE, CHANGELOG
        - code generation with php and twig templates
        - VCS integration: .gitignore, commits history
        - code quality: php-cs-fixer, VersionEye
        - testing: codeception

        And more planned. See [ROADMAP](https://github.com/hiqdev/hidev/blob/master/ROADMAP.md).

require:
    hiqdev/hidev-hiqdev: "*@dev"
    hiqdev/hidev-php:    "*@dev"
